### ISSUE TITLE
Slow text entry and relay publishing

### ISSUE THREAD

**Issue by dmnyc** [nostur-com/nostur-ios-public#3]
Version: 1.8.0 (195)

Screen capture:
https://github.com/nostur-com/nostur-ios-public/assets/3638467/787ae9cf-c095-456e-b6ff-f04ef8fa0820

**Comment by fabianfabian** [comment]
I'm wondering if this could be related to the amount of relays, can you try receiving from 2-3 max, and maybe limit sending to no more than 5, just as a test.

And maybe remove or disable wss://nostr-relay.untethr.me in your list because it looks like it has a trailing tab character (\\t), not sure if that breaks things.

You can do this in Nostur and it won't affect your relay settings in other clients, Nostur only imports your relay configuration it doesn't publish or overwrite yet.

Here is my relay configuration as an example:
Only 2 receiving (down arrow)
And 5 for sending (up arrow)

![image](https://github.com/nostur-com/nostur-ios-public/assets/343640/e50abcee-9ee2-4350-ace7-073999a2098e)

You can tap the arrows to toggle.

**Comment by fabianfabian** [comment]
@dmnyc is this still happening in recent versions?

**Comment by dmnyc** [comment]
Seems much faster today.

**Comment by fabianfabian** [comment]
version 1.9.0 or build 222 has improved this even further. Should be fixed, if not we can reopen this.
